name: lint-and-test
kind: pipeline
type: docker

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: setup
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.11_poetry_1.5.0
    commands:
      - make setup.project
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD

  - name: lints-quality-tests
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.11_poetry_1.5.0
    commands:
      - make lints.ci
      - make test.unit
      - make test.integration
    environment:
      APP_ENV: development

  - name: code-analysis
    image: plugins/sonarqube-drone-plugin
    environment:
      SONAR_HOST:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN

---
name: publish-release
kind: pipeline
type: docker
depends_on:
  - lint-and-test
trigger:
  event:
    - push
    - pull_request
    - tag


when_prod_release: &when_prod_release
  when:
    branch:
      - main
    event:
      - push


steps:
  - name: docker-prep
    image: harbor.shipttech.com/plugins/dockerspec
    pull: always

  - name: docker-build-and-push
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      ARTIFACTORY_PYPI_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      ARTIFACTORY_PYPI_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    settings:
      build_args_from_env:
        - GITHUB_TOKEN
        - ARTIFACTORY_PYPI_USERNAME
        - ARTIFACTORY_PYPI_PASSWORD
      registry: harbor.shipttech.com
      env_file: docker_args

#  - name: artifactory-poetry-publish
#    <<: *when_prod_release
#    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.11_poetry_1.5.0
#    environment:
#      POETRY_HTTP_BASIC_SHIPT_DEPLOY_USERNAME:
#        from_secret: ARTIFACTORY_PYPI_USERNAME
#      POETRY_HTTP_BASIC_SHIPT_DEPLOY_PASSWORD:
#        from_secret: ARTIFACTORY_PYPI_PASSWORD
#    commands:
#      - poetry config repositories.shipt-deploy https://artifactory.gcp.shipttech.com/artifactory/api/pypi/pypi-local
#      - poetry publish --repository shipt-deploy --build
