name: Lints-Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down

jobs:
  test-os:

    name: test ${{ matrix.os }}-${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        poetry-version: ["1.5.1"]
        python-version: ["3.9", "3.10","3.11.5"]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      - name: Set up Rust
        run: rustup override set stable && rustup update

      - name: Install clippy
        run: rustup component add clippy

      - name: cache rust
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.python-version }}-v1

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run : |
          poetry export --format=requirements.txt > requirements.txt
          pip install -r requirements.txt
        
      - name: Run cargo tests
        run: |
          make format
          make lints
          make test.unit
        env:
          RUST_BACKTRACE: 1


  test-ubuntu-pypy:
    name: test ubuntu-${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        poetry-version: ["1.5.1"]
        python-version: ["pypy3.9", "pypy3.10"]
        os: [ubuntu]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      - name: Set up Rust
        run: rustup override set stable && rustup update

      - name: Install clippy
        run: rustup component add clippy

      - name: cache rust
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.python-version }}-v1

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo "$GITHUB_WORKSPACE/opsml_cli/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run : |
          sudo apt-get install python3-pkgconfig libopenblas-dev
          make setup.project
        
      - name: Run cargo tests
        run: |
          . .venv/bin/activate
          make format
          make lints
          make test.unit
        env:
          RUST_BACKTRACE: 1

  test-build:
    needs: [test-os]
    name: build - ubuntu - ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, x86]
        manylinux: [auto]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -U twine

      - name: build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          args: --release --out dist --interpreter 3.11
          rust-toolchain: stable
          docker-options: -e CI
          before-script-linux: | # ref: https://github.com/sfackler/rust-openssl/issues/2036#issuecomment-1724324145
            # If we're running on rhel centos, install needed packages.
            if command -v yum &> /dev/null; then
                yum update -y && yum install -y perl-core openssl openssl-devel pkgconfig libatomic

                # If we're running on i686 we need to symlink libatomic
                # in order to build openssl with -latomic flag.
                if [[ ! -d "/usr/lib64" ]]; then
                    ln -s /usr/lib/libatomic.so.1 /usr/lib/libatomic.so
                fi
            else
                # If we're running on debian-based system.
                sudo apt update -y && sudo apt-get install -y libssl-dev openssl pkg-config
            fi

        env:
          RUST_BACKTRACE: 1

      - run: ls -lh dist/

      - run: twine check --strict dist/*